1. **使用Tensor初始化一个1×3的矩阵M和一个2×1的矩阵N，对两矩阵进行减法操作（要求实现三种不同的形式），给出结果并分析三种方式的不同（如果出现报错，分析报错的原因），同时需要指出在计算过程中发生了什么**

In [22]:
# 初始化矩阵M和矩阵N
import torch
M = torch.randint(10,(1,3))
N = torch.randint(10,(2,1))

print(M)
print(N)

tensor([[9, 0, 4]])
tensor([[5],
        [7]])


In [38]:
# 方式一：torch.sub(M,N)
print(torch.sub(M,N))

# 方式二：M - N
print(M-N)

# 方式三：M.sub(N)
print(M.sub(N))

"""三种方式都引发了tensor的广播机制，因为M,N的维度不相同，所以N被广播成([[5,0,0],[7,0,0]])后，M的对应元素与广播后的N的对应元素相减"""

tensor([[ 4, -5, -1],
        [ 2, -7, -3]])
tensor([[ 4, -5, -1],
        [ 2, -7, -3]])
tensor([[ 4, -5, -1],
        [ 2, -7, -3]])


'三种方式都引发了tensor的广播机制，因为M,N的维度不相同，所以N被广播成([[5,0,0],[7,0,0]])后，M的对应元素与广播后的N的对应元素相减'

2. ** 利用Tensor创建两个大小分别3×2和4×2的随机数矩阵P和Q，要求服从均值为0，标准差0.01为的正态分布；**

In [46]:
P = torch.normal(mean=0,std=0.01+torch.zeros(3,2))
Q = torch.normal(mean=0,std=0.01+torch.zeros(4,2))

print(P)
print(Q)

tensor([[-0.0025, -0.0093],
        [-0.0051, -0.0005],
        [ 0.0136, -0.0216]])
tensor([[ 0.0048, -0.0015],
        [-0.0185,  0.0161],
        [ 0.0027,  0.0143],
        [-0.0027,  0.0117]])


** 对第二步得到的矩阵Q进行形状变换得到Q的转置Q.T；**

In [47]:
Q_transpose = Q.T

**对上述得到的矩阵P和矩阵Q.T求内积**

In [49]:
print(P.mm(Q_transpose))

tensor([[ 1.7650e-06, -1.0462e-04, -1.3989e-04, -1.0230e-04],
        [-2.4035e-05,  8.7279e-05, -2.1064e-05,  7.8902e-06],
        [ 9.7090e-05, -6.0015e-04, -2.7147e-04, -2.8831e-04]])


**3.给定公式y3 = y1 + y2 = x^2 + x^3，且x = 1。利用学习得到的Tensor的相关知识，求y3对的梯度x，即dy3/dx。**  
**要求在计算过程中，在计算x^3时中断梯度的追踪，观察结果并进行原因分析**

In [51]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2 
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2

y3.backward()
print(x.grad)

tensor(2.)
