In [7]:
import torch
import numpy as np

* 人工神经元

In [1]:
def neurons(X,w,b):
    z = torch.mm(X,w)+b
    return F.relu(z)

* 激活函数

**手动实现sigmoid激活函数**

In [5]:
input_x = torch.randn(4)
input_x

tensor([-0.7091, -0.9401, -1.6712,  0.5745])

In [8]:
def sigmoid(x):
    return 1.0/(1.0+np.exp(-x))
sigmoid(input_x)

tensor([0.3298, 0.2809, 0.1583, 0.6398])

**调用pytorch实现sigmoid激活函数**

In [9]:
output = torch.sigmoid(input_x)
print(output)

tensor([0.3298, 0.2809, 0.1583, 0.6398])


**手动实现tanh激活函数**

In [10]:
input_x = torch.randn(4)
input_x

tensor([ 0.4388,  0.4930,  1.1158, -0.4560])

In [13]:
def fun_tanh(x):
    return (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
fun_tanh(input_x)

tensor([ 0.4126,  0.4566,  0.8061, -0.4268])

**调用pytorch实现的tanh激活函数**

In [14]:
output = torch.tanh(input_x)
print(output)

tensor([ 0.4126,  0.4566,  0.8061, -0.4268])


**手动实现ReLU激活函数**

In [15]:
input_x = torch.randn(4)
input_x

tensor([-0.5976,  0.4741, -0.9432, -0.2834])

In [16]:
def fun_relu(x):
    x = np.where(x>0,x,0)
    return torch.tensor(x)
fun_relu(input_x)

tensor([0.0000, 0.4741, 0.0000, 0.0000])

**调用pytorch实现ReLU激活函数**

In [18]:
output = torch.nn.functional.relu(input_x)
print(output)

tensor([0.0000, 0.4741, 0.0000, 0.0000])


**手动实现leakyReLU激活函数**

In [20]:
input_x = torch.randn(4)
input_x

tensor([-0.0900, -0.4123,  0.2545, -0.5169])

In [21]:
def fun_leakyrelu(x,alpha):
    x = np.where(x>0,x,alpha*x)
    return torch.tensor(x)
fun_leakyrelu(input_x,0.2)

tensor([-0.0180, -0.0825,  0.2545, -0.1034])

**调用pytorch实现的leakyReLU激活函数**

In [22]:
output = torch.nn.functional.leaky_relu(input_x,0.2)
print(output)

tensor([-0.0180, -0.0825,  0.2545, -0.1034])


**手动实现eLU激活函数**

In [25]:
input_x = torch.randn(4)
input_x

tensor([-0.7756, -0.5415,  0.0772, -0.2255])

In [26]:
def fun_elu(x,alpha):
    x = np.where(x>0,x,alpha*(np.exp(x)-1))
    return torch.tensor(x)
fun_elu(input_x,0.2)

tensor([-0.1079, -0.0836,  0.0772, -0.0404])

* 优化器的使用

**手动实现SGD**

In [27]:
def SGD(params,lr):
    for param in params:
        param.data -= lr*param.grad

**pytorch如何使用SGD**

In [31]:
optimizer = torch.optim.SGD(model.parameters(),lr)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output,target)
    optimzer.zero_grad()
    loss.backward()
    optimizer.step()

AttributeError: 'NoneType' object has no attribute 'parameters'